language:
  - php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  global:
    - CFLAGS="-O0 --coverage -Wall -Wextra -Werror -Wno-unused-parameter"
    - LDFLAGS="--coverage"
    - EXTRA_LDFLAGS='-precious-files-regex \.gcno\$$'
    - NO_INTERACTIVE=1

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - phpize && ./configure --silent && make --silent

script:
  - make test

after_success:
  - cp ./.libs/*.gc{da,no} ./
  - bash <(curl -s https://codecov.io/bash)
