name: Build and Test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  CFLAGS: "-O0 --coverage -Wall -Wextra -Werror -Wno-unused-parameter"
  LDFLAGS: "--coverage"
  EXTRA_LDFLAGS: '-precious-files-regex \.gcno\$$'
  NO_INTERACTION: "1"
  REPORT_EXIT_STATUS: "1"

jobs:
  ci:
    permissions:
      contents: read
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: true
      matrix:
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    name: "Build and Test (PHP ${{ matrix.php }})"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the source code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      - name: Set up PHP
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # 2.24.0
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Build
        run: phpize && ./configure --silent && make --silent

      - name: Run tests
        run: make test

      - name: Upload coverage
        run: |
          cp ./.libs/*.gc{da,no} ./
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.php == '7.3'
