name: Build and Test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  CFLAGS: "-O0 --coverage -Wall -Wextra -Werror -Wno-unused-parameter"
  LDFLAGS: "--coverage"
  EXTRA_LDFLAGS: '-precious-files-regex \.gcno\$$'
  NO_INTERACTION: "1"
  REPORT_EXIT_STATUS: "1"

jobs:
  ci:
    permissions:
      contents: read
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: true
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    name: "Build and Test (PHP ${{ matrix.php }})"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up PHP
        uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # 2.34.1
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Build
        run: phpize && ./configure --silent && make --silent

      - name: Run tests
        run: make test
